#!/bin/bash

cd /home/papers/dev/papers/
source env/bin/activate
# envuidgid sets $UID and $GID of process to the user, but the process is
# started as root. I believe this is necessary if we are running the service
# at a low port number. But since we aren't, we can use setuidgid.
exec setuidgid papers python manage.py runfcgi method=threaded host=127.0.0.1 port=8088 pidfile=fcgi.pid minspare=1 maxspare=2 daemonize=false
